version: '2'
services:
  web:
    build: ./web
    ports:
      - "8003:3003"
    volumes:
      - './web/src:/opt/work/web/'
  #py:
  #  build: ./py
  #  ports:
  #   - "5000:5000"
  #  volumes:
  #   - ./py:/code


